### ISSUE TITLE
Isolate for all domains

### ISSUE THREAD

**Issue by zaibas** [Mimieam/TabSorter2#15]
Could you add a button to use the isolate function on all domains rather than just the currently selected 
one?  
To clarify the end result would be a window for each domain with all the tabs with that domain in it 

thank you very much for your work on this great addon

**Comment by Mimieam** [comment]
This has actually is being implemented in the next version - with the constraint that a domain needs to have at least 3 tabs to be pulled in its own window and all others will be merged into one, the constraint could be optional later on :)

**Comment by Mimieam** [comment]
This is now implemented :)
