### ISSUE TITLE
Make TabSorter2's icon more visible

### ISSUE THREAD

**Issue by dfrechette** [Mimieam/TabSorter2#2]
I have a dark gray theme which matches your icon's color. It's very hard to know it's there. I look for the blue label whenever I need to use the feature. See the following screenshot. 

<img width="600" alt="screen shot 2017-10-30 at 23 50 37" src="https://user-images.githubusercontent.com/14079/32206712-35ec6db0-bdcd-11e7-92f0-68430e6a4c67.png">

**Comment by Mimieam** [comment]
Hi @dfrechette, thanks for pointing this out, I will look into providing an option to switch Icons :)

**Comment by Mimieam** [comment]
The latest version has now a more visible Icon :)
