### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by q2p** [Mimieam/TabSorter2#22]
Why do you need these permissions?
Any source code?
![image](https://user-images.githubusercontent.com/11664429/73235107-8db17e00-41bf-11ea-9e59-3eb713f31e46.png)

**Comment by Mimieam** [comment]
Yes this was due to the update to 1.1 
the only difference from the previous version is that we are now using publicsuffix to get the list of domain suffix available worldwide.
Download - to save/upload
extensions - bundle to manage tabs and window - TS2 doesn't look at anything else like other apps, extensions or themes - but that's how chrome present this

let me know if you need more details

**Comment by q2p** [comment]
No source -> no update.
An extentions developed to sort tabs should only request a permission for tabs.
Well... too bad, now I have to uninstall it.

**Comment by Mimieam** [comment]
> No source -> no update.

hmm we wouldn't be having this discussion if an update didn't triggered this, but ok 😅

>An extension developed to sort tabs should only request a permission for tabs.

Agree to disagree on that, If you would like to only sort Tabs - then by all means i recommend using [This Extension](https://chrome.google.com/webstore/detail/tab-sorter/nlnkcinjjeoojlhdiedbbolilahmnldj?hl=en) it does the job quite nicely

TS2 uses the following permission to do what it needs to do - especially when it comes to finding work around some of chrome API weird behaviors/bugs.

```
"permissions": [
    "activeTab",
    "downloads",
    "management",
    "notifications",
    "tabs",
    "storage",
    "https://publicsuffix.org/*",
    "system.display"
  ],

```
- feel free to look at the chrome extension API for details about those. I would guess that the "management" permission is the scary one to most -but it is only used to get access to the **onInstalled** and **onEnabled** [events](https://developer.chrome.com/extensions/management#event-onInstalled) used for auto sorting and such.

I always strive to improve TS2 so I will keep this in mind for the next update an try to minimize the number of permissions.

@q2p Thank you for using TS2 till now and sorry to see you leave.
