### ISSUE TITLE
TS2 menu broken

### ISSUE THREAD

**Issue by khmseu** [Mimieam/TabSorter2#23]
The TS2 menu has stopped working. I only get a dark rectangle about one line high, and clicking
 doesn't seem to do a thing.
![Bildschirmfoto_2020-02-01_14-12-18](https://user-images.githubusercontent.com/16058485/73592679-0e90b280-44fd-11ea-92d2-ef7c708b7bf9.png)

**Comment by khmseu** [comment]
Hmm. I'm seeing a weird error. Chrome says

> Cannot load extension with file or directory name `_metadata`. Filenames starting with "`_`" are reserved for use by the system.

marking this piece of source
```
   "background": {
      "scripts": [ "bower_components/file-saver/FileSaver.min.js", "bower_components/urijs/src/URI.min.js", "scripts/commons.js", "scripts/background.js" ]
   },

```
where I fail to see _metadata ...

**Comment by Mimieam** [comment]
Weird indeed - nothing was changed on this side of things.
Which version of Chrome are you using?

**Comment by khmseu** [comment]
This started several upgrades ago. Currently:

Chromium
Version 75.0.3770.90 (Offizieller Build) Built on Ubuntu , running on Ubuntu 18.10 (64-Bit)

**Comment by Mimieam** [comment]
I will be looking into that, sorry for the inconvenience :(

**Comment by Mimieam** [comment]
sorry for the massive delay on this... it is now fixed pending the 2022 - summer release.
