### ISSUE TITLE
Idea: Sort / merge by CPU usage

### ISSUE THREAD

**Issue by toybuilder** [Mimieam/TabSorter2#27]
I have found that certain websites are consistently CPU-heavy and will actually make my computer run hot if they are left open. 
(Various TV-network-news sites being the worst offenders.) 

Tab sorter 2 has been great for letting me merge/sort and then easily identify and kill the pages that I know to be CPU-heavy.

I don't know if there's an API that would let you get usable information from Chrome's task manager, but if it was possible to merge/split/sort based on average CPU load (and/or perhaps also memory usage), it might be really helpful for Chromeaholics like me prune what's left open.

Thanks for a great product, btw!

**Comment by Mimieam** [comment]
That's an interesting idea - I'm currently busy creating a light version to deal with chrome new requirements of permission but I will look into this for the next major release

**Comment by Mimieam** [comment]
Sadly this is not currently possible as the [chrome process API](https://developer.chrome.com/docs/extensions/reference/processes/#type-Process) is still only available on the Dev channel - a workaround for this would involve trying to scrape one of their internal page... which can't be done from within an extension ...
I will close this issue for now, but I'm willing to reopen it if/when a viable workaround arise
