### ISSUE TITLE
Options to automatically sort the tabs by title

### ISSUE THREAD

**Issue by akai1831** [Mimieam/TabSorter2#4]
Hi, Thanks from this plugin anyway.

Could you add an option to automatically sort the tabs (by Tab Title) when the Chrome starts. This is great in order not to intervene user with the Browser for Dashboard purposes

**Comment by akai1831** [comment]
If this could not be done, you can adapt the idea from https://github.com/100/Tab-Organizer
That plugin can sort the tabs within an interval time but it lacks to sort tabs by title

**Comment by akai1831** [comment]
Great to hear. I'm going to use this in Dashboard. Thanks!

**Comment by akai1831** [comment]
BUMP

**Comment by akai1831** [comment]
Ping @mimieam

**Comment by Mimieam** [comment]
I have been fairly busy lately, but I'm hoping to have a new release around mid January at the latest :)

**Comment by akai1831** [comment]
Trying to get from here.
Thanks

**Comment by akai1831** [comment]
Its been a year, do we have an update?

**Comment by Mimieam** [comment]
Yes this is finally done! A big update is on it's way once i fix the issues with chrome API changes

**Comment by akai1831** [comment]
Great! I'm trying to install it via Chrome Web Store but it is outdated, what's important to me is to sort the tabs by title automatically. I'm not using the split feature.

Thanks
