### ISSUE TITLE
Tab sorting not working

### ISSUE THREAD

**Issue by masonc15** [Mimieam/TabSorter2#40]
Hi,

I think this might be caused by the most recent 2.2.8 update (since I've never had any issues previously) but tab sorting is currently not working for me at all.  Thanks!

**Comment by Mimieam** [comment]
Hi @masonc15,
Thanks for reporting this, I'm actively investigating why the deployed versions 2.2.0 and 2.2.8 keep failing when installed from the chrome store. 

In the meantime time I have submitted 2.2.11 which downgrades back to the old 2.1.0. 
Hopefully this should be deployed shortly within a few hours. A reloading/refreshing might be needed.

**Comment by Mimieam** [comment]
2.2.11 is live - you might need to updating and click the refreshing button

<img width="59" alt="image" src="https://user-images.githubusercontent.com/834291/229323392-bfaf102d-8780-47a4-a8f1-849b11054111.png">

**Comment by Mimieam** [comment]
Closing this - 2.2.12 - is now live :)
