### ISSUE TITLE
Sticky tabs

### ISSUE THREAD

**Issue by 4picht** [Mimieam/TabSorter2#6]
Please support sticky tabs :)

**Comment by Mimieam** [comment]
Hi There,  I'm not sure what you mean, are you referring to Pinned tabs? 
Any example would be much appreciated :)

**Comment by 4picht** [comment]
Exactly, thats what I'm talking about, my browser is not in English so I guessed how they would be named in the English version.

My "problem": I have one window with a lot of pinned tabs, I'd like those to stay pinned, even if I combine all tabs in one window, currently they get unpinned and mixed with the rest of the tabs.

I would usually offer to send a patch, but there seems to be no source code available for this extension. :sweat_smile:

**Comment by Mimieam** [comment]
ha make sense, I will had that to my  todo list for the next release :)

**Comment by Mimieam** [comment]
alright, this is actually done now 😁 the next release will have it! thanks for your patience :)
